event_args = {"Attack": ['Attacker', 'Target', 'Place', 'Instrument', 'Time-Within', 'Time-Holds', 'Time-Starting', 'Time-Before', 'Time-After', 'Time-Ending', 'Time-At-Beginning', 'Time-At-End', 'Victim', 'Agent'],
"End-Position":['Person', 'Entity', 'Position', 'Time-Within', 'Place', 'Time-Starting', 'Time-Ending', 'Time-After', 'Time-At-End', 'Time-Holds', 'Time-Before'],
"Marry": ['Person', 'Time-Within', 'Place', 'Time-Holds', 'Time-Before'],
"Die": ['Victim', 'Agent', 'Place', 'Time-Within', 'Instrument', 'Time-Before', 'Time-Starting', 'Time-Ending', 'Time-After', 'Time-At-Beginning', 'Time-Holds', 'Person'],
"Pardon": ['Adjudicator', 'Defendant', 'Time-At-End', 'Place'],
"Start-Org": ['Org', 'Agent', 'Place', 'Time-Within', 'Time-Starting', 'Time-After', 'Time-Before'],
"Divorce": ['Person', 'Time-Within', 'Place'],
"Trial-Hearing": ['Defendant', 'Crime', 'Adjudicator', 'Time-Within', 'Place', 'Prosecutor', 'Time-Starting', 'Time-Holds', 'Time-At-End'],
"Execute": ['Person', 'Agent', 'Place', 'Time-Within', 'Crime', 'Time-At-Beginning', 'Time-After'],
"End-Org": ['Org', 'Place', 'Time-Within', 'Time-After', 'Time-Holds', 'Time-At-Beginning'],
"Acquit": ['Defendant', 'Adjudicator', 'Crime', 'Time-Within'],
"Transport": ['Artifact', 'Destination', 'Origin', 'Time-Within', 'Agent', 'Vehicle', 'Time-Holds', 'Time-Starting', 'Time-At-End', 'Time-Ending', 'Time-After', 'Time-Before', 'Time-At-Beginning', 'Victim', 'Place'],
"Be-Born": ['Person', 'Time-Within', 'Place', 'Time-Holds'],
"Start-Position": ['Person', 'Entity', 'Position', 'Time-Within', 'Place', 'Time-Starting', 'Time-After', 'Time-At-Beginning', 'Time-Holds', 'Time-Before'],
"Sue":  ['Defendant', 'Plaintiff', 'Adjudicator', 'Time-Within', 'Crime', 'Place', 'Time-Holds'],
"Declare-Bankruptcy": ['Org', 'Time-Within', 'Time-At-Beginning', 'Time-After', 'Place'],
"Fine":  ['Entity', 'Money', 'Adjudicator', 'Time-Within', 'Place', 'Crime'],
"Appeal":['Plaintiff', 'Adjudicator', 'Crime', 'Time-Within', 'Place', 'Time-Holds'],
"Injure": ['Victim', 'Place', 'Agent', 'Instrument', 'Time-Within'],
"Elect": ['Person', 'Time-Within', 'Place', 'Entity', 'Position', 'Time-Starting', 'Time-At-Beginning', 'Time-Holds', 'Time-Before'],
"Charge-Indict": ['Crime', 'Defendant', 'Prosecutor', 'Place', 'Time-Within', 'Adjudicator', 'Time-Ending', 'Time-Before'],
"Convict": ['Defendant', 'Crime', 'Time-Within', 'Adjudicator', 'Place', 'Time-At-Beginning'],
"Nominate": ['Person', 'Agent', 'Position', 'Time-Within'],
"Sentence": ['Defendant', 'Sentence', 'Crime', 'Adjudicator', 'Place', 'Time-Within', 'Time-Starting', 'Time-At-End'],
"Merge-Org":['Org', 'Time-Ending'],
"Release-Parole": ['Person', 'Entity', 'Time-Within', 'Crime', 'Place', 'Time-After'],
"Transfer-Ownership": ['Artifact', 'Buyer', 'Seller', 'Time-Within', 'Place', 'Beneficiary', 'Price', 'Time-Before', 'Time-At-Beginning', 'Time-Ending'],
"Extradite": ['Person', 'Destination', 'Origin', 'Agent', 'Time-Within'],
"Arrest-Jail": ['Person', 'Agent', 'Place', 'Crime', 'Time-Within', 'Time-Holds', 'Time-Ending', 'Time-At-Beginning', 'Time-Starting', 'Time-Before'],
"Meet": ['Entity', 'Time-Within', 'Place', 'Time-Holds', 'Time-Starting', 'Time-Ending', 'Time-After', 'Time-At-Beginning'],
"Demonstrate": ['Entity', 'Place', 'Time-Within', 'Time-Starting', 'Time-At-End'],
"Phone-Write":['Entity', 'Time-Within', 'Place', 'Time-Holds', 'Time-Starting', 'Time-After', 'Time-Before'],
"Transfer-Money": ['Giver', 'Recipient', 'Money', 'Beneficiary', 'Time-Within', 'Place', 'Time-Holds', 'Time-Starting', 'Time-After', 'Time-Before']}

entity2id = {'I-Boundary': 80, 'I-Land': 58, 'B-Address': 53, 'I-Sports': 96, 'B-Sports': 95, 'B-State-or-Province': 47,
             'B-Commercial': 59, 'I-Address': 54, 'I-Air': 12, 'I-Media': 74, 'B-Indeterminate': 13, 'B-Underspecified': 89,
             'B-Money': 49, 'I-Nuclear': 32, 'I-Government': 26, 'I-Biological': 8, 'I-Crime': 38, 'B-Crime': 37, 'B-Media': 73,
             'B-Boundary': 79, 'B-Blunt': 75, 'I-Path': 72, 'I-Non-Governmental': 20, 'I-Population-Center': 2, 'I-Celestial': 84,
             'B-Group': 45, 'B-Water': 101, 'B-Entertainment': 77, 'I-Continent': 22, 'B-Water-Body': 3, 'B-Medical-Science': 55,
             'B-Region-General': 23, 'O': 0, 'B-Educational': 99, 'I-Group': 46, 'B-Individual': 39, 'I-Land-Region-Natural': 16,
             'I-Projectile': 34, 'B-Chemical': 91, 'I-Subarea-Vehicle': 52, 'I-Medical-Science': 56, 'I-Exploding': 42, 'B-Air': 11,
             'I-URL': 70, 'I-Sentence': 28, 'I-Job-Title': 30, 'I-Commercial': 60, 'B-Special': 17, 'B-Path': 71,
             'I-Building-Grounds': 36, 'I-Educational': 100, 'I-Nation': 6, 'B-Nuclear': 31, 'B-E-Mail': 103,
             'I-County-or-District': 44, 'B-Plant': 93, 'I-Chemical': 92, 'B-Airport': 81, 'B-Building-Grounds': 35, 'B-URL': 69,
             'B-Nation': 5, 'I-Plant': 94, 'I-Blunt': 76, 'I-Sharp': 66, 'I-Water-Body': 4, 'B-Phone-Number': 85,
             'I-Underspecified': 90, 'B-Population-Center': 1, 'I-Region-General': 24, 'B-Subarea-Facility': 67, 'B-Religious': 9,
             'I-E-Mail': 104, 'I-Airport': 82, 'I-GPE-Cluster': 88, 'B-Government': 25, 'I-Percent': 62, 'I-State-or-Province': 48,
             'I-Money': 50, 'I-Water': 102, 'I-Time': 64, 'I-Subarea-Facility': 68, 'B-Exploding': 41, 'B-Region-International': 97,
             'I-Indeterminate': 14, 'I-Special': 18, 'B-Shooting': 105, 'B-Percent': 61, 'B-Celestial': 83, 'B-Non-Governmental': 19,
             'B-Sharp': 65, 'I-Entertainment': 78, 'I-Individual': 40, 'B-Land-Region-Natural': 15, 'B-Sentence': 27,
             'B-Biological': 7, 'B-Subarea-Vehicle': 51, 'B-Time': 63, 'I-Phone-Number': 86, 'B-Projectile': 33, 'I-Religious': 10,
             'I-Shooting': 106, 'B-Job-Title': 29, 'B-Land': 57, 'B-GPE-Cluster': 87, 'B-County-or-District': 43, 'B-Continent': 21,
             'I-Region-International': 98}

pos2id = {'FW': 31, 'RB': 34, 'WDT': 1, 'RP': 2, 'WRB': 3, 'UH': 24, '``': 25, 'SYM': 4, 'VBP': 27, 'NN': 5, 'PDT': 28, 'JJS': 26,
          'JJR': 6, '$': 7, 'DT': 8, 'VBZ': 9, 'RBR': 30, 'NNP': 10, ',': 29, 'NNPS': 11, 'O': 0, 'PRP': 33, 'TO': 12, 'WP$': 36,
          'JJ': 37, 'LS': 13, 'VB': 14, '.': 41, 'NNS': 38, 'EX': 15, 'RBS': 16, ':': 35, 'VBG': 17, "''": 18, 'IN': 19, 'CD': 42,
          'MD': 20, 'CC': 21, 'POS': 32, 'VBD': 22, 'VBN': 23, 'WP': 39, 'PRP$': 40}

label2idx = {'0': 0,
  '1': 1,
  '10': 10,
  '11': 11,
  '12': 12,
  '13': 13,
  '14': 14,
  '15': 15,
  '16': 16,
  '2': 2,
  '3': 3,
  '4': 4,
  '5': 5,
  '6': 6,
  '7': 7,
  '8': 8,
  '9': 9}

idx2label = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16"]

tag2label = {'B-Elect-T': 5, 'B-Giver': 101, 'I-Time-Holds': 122, 'B-Target': 83, 'B-Time-Starting': 97, 'B-Buyer': 73,
             'B-Trial-Hearing-T': 27, 'B-Fine-T': 21, 'I-Marry-T': 10, 'I-Agent': 86, 'I-Victim': 130, 'I-Die-T': 16,
             'B-Adjudicator': 93, 'I-Elect-T': 6, 'B-Org': 133, 'I-Start-Org-T': 4, 'I-Declare-Bankruptcy-T': 50, 'B-Recipient': 79,
             'B-Demonstrate-T': 51, 'I-Demonstrate-T': 52, 'B-Transfer-Ownership-T': 33, 'I-Injure-T': 36, 'B-Position': 67,
             'B-Transfer-Money-T': 19, 'I-Person': 90, 'B-Execute-T': 55, 'I-Extradite-T': 46, 'I-Arrest-Jail-T': 2, 'B-Sue-T': 47,
             'B-Place': 113, 'B-Destination': 111, 'I-Money': 110, 'I-Phone-Write-T': 14, 'B-Appeal-T': 53, 'B-Divorce-T': 63,
             'I-Sentence-T': 40, 'B-Be-Born-T': 43, 'I-Artifact': 88, 'B-Acquit-T': 61, 'B-Origin': 103, 'I-Time-At-Beginning': 70,
             'B-Price': 115, 'I-Buyer': 74, 'B-Money': 109, 'B-Time-Ending': 95, 'I-Start-Position-T': 42, 'I-Be-Born-T': 44,
             'I-Release-Parole-T': 26, 'I-Time-Within': 72, 'I-Transfer-Money-T': 20, 'B-Victim': 129, 'I-Time-Before': 82, 'O': 0,
             'I-Destination': 112, 'B-Time-At-End': 119, 'B-Agent': 85, 'I-Origin': 104, 'B-Nominate-T': 23,
             'I-Transfer-Ownership-T': 34, 'B-Attacker': 135, 'I-Attacker': 136, 'B-Declare-Bankruptcy-T': 49, 'I-Vehicle': 78,
             'I-Fine-T': 22, 'I-Appeal-T': 54, 'B-Extradite-T': 45, 'I-Nominate-T': 24, 'B-Time-Before': 81, 'B-Sentence': 99,
             'I-Plaintiff': 118, 'B-Time-At-Beginning': 69, 'I-Crime': 124, 'B-Arrest-Jail-T': 1, 'B-Charge-Indict-T': 29,
             'I-Adjudicator': 94, 'B-Convict-T': 57, 'I-Time-At-End': 120, 'B-Die-T': 15, 'B-Prosecutor': 131, 'B-Marry-T': 9,
             'B-Person': 89, 'B-Vehicle': 77, 'I-Execute-T': 56, 'I-Transport-T': 38, 'I-Position': 68, 'I-Target': 84,
             'B-Time-After': 75, 'B-Release-Parole-T': 25, 'B-Phone-Write-T': 13, 'B-Beneficiary': 107, 'I-Time-After': 76,
             'I-Divorce-T': 64, 'I-Trial-Hearing-T': 28, 'B-Plaintiff': 117, 'B-Start-Position-T': 41, 'B-Defendant': 105,
             'B-Artifact': 87, 'I-Prosecutor': 132, 'I-Merge-Org-T': 60, 'B-End-Org-T': 7, 'I-End-Org-T': 8, 'B-Time-Holds': 121,
             'I-Defendant': 106, 'I-Attack-T': 66, 'I-Instrument': 92, 'B-Start-Org-T': 3, 'B-Merge-Org-T': 59, 'I-Sentence': 100,
             'B-End-Position-T': 31, 'B-Instrument': 91, 'I-Charge-Indict-T': 30, 'I-Seller': 128, 'I-Place': 114, 'B-Injure-T': 35,
             'I-Sue-T': 48, 'I-Pardon-T': 12, 'I-Time-Starting': 98, 'I-Price': 116, 'I-Org': 134, 'I-End-Position-T': 32,
             'I-Recipient': 80, 'I-Entity': 126, 'I-Acquit-T': 62, 'B-Time-Within': 71, 'I-Beneficiary': 108, 'I-Giver': 102,
             'B-Attack-T': 65, 'B-Meet-T': 17, 'B-Crime': 123, 'B-Entity': 125, 'B-Pardon-T': 11, 'I-Convict-T': 58, 'I-Meet-T': 18,
             'I-Time-Ending': 96, 'B-Sentence-T': 39, 'B-Transport-T': 37, 'B-Seller': 127}

# label2idx = {'B-0': 0,
#  'B-1': 2,
#  'B-10': 20,
#  'B-11': 22,
#  'B-12': 24,
#  'B-13': 26,
#  'B-14': 28,
#  'B-15': 30,
#  'B-2': 4,
#  'B-3': 6,
#  'B-4': 8,
#  'B-5': 10,
#  'B-6': 12,
#  'B-7': 14,
#  'B-8': 16,
#  'B-9': 18,
#  'I-0': 1,
#  'I-1': 3,
#  'I-10': 21,
#  'I-11': 23,
#  'I-12': 25,
#  'I-13': 27,
#  'I-14': 29,
#  'I-15': 31,
#  'I-2': 5,
#  'I-3': 7,
#  'I-4': 9,
#  'I-5': 11,
#  'I-6': 13,
#  'I-7': 15,
#  'I-8': 17,
#  'I-9': 19,
#  'O': 32}
#
# idx2label = ['B-0',
#   'I-0',
#   'B-1',
#   'I-1',
#   'B-2',
#   'I-2',
#   'B-3',
#   'I-3',
#   'B-4',
#   'I-4',
#   'B-5',
#   'I-5',
#   'B-6',
#   'I-6',
#   'B-7',
#   'I-7',
#   'B-8',
#   'I-8',
#   'B-9',
#   'I-9',
#   'B-10',
#   'I-10',
#   'B-11',
#   'I-11',
#   'B-12',
#   'I-12',
#   'B-13',
#   'I-13',
#   'B-14',
#   'I-14',
#   'B-15',
#   'I-15',
#   'O']

# classes for train and dev.
classes = ['Attack', 'Transport','Die','Meet','End-Position','Transfer-Money','Elect','Injure','Transfer-Ownership','Phone-Write']
# classes for test.
classes_test = ['Start-Position','Trial-Hearing','Charge-Indict','Sentence','Arrest-Jail','Marry','Demonstrate','Sue','Convict','Be-Born','Start-Org','Release-Parole',
 'Appeal','Declare-Bankruptcy','End-Org','Divorce','Fine',
# 'Execute',
# 'Merge-Org',
# 'Nominate',
 #'Extradite',
 #'Acquit',
 #'Pardon'
  ]
